

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp 
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Deploy Experiment
      uses: Azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: 4668507d-0a5b-4ef7-9ca7-a10f2cc3103b
        region: eastus
        resourceGroupName: deployApp
        template: /deploy/templates/experiment.json
        deploymentMode: Incremental
      
    - name: App Insights experiment start
      uses: wictorwilen/application-insights-action@v1
      with:
        applicationId: 0e3aa4b6-48d3-4505-b65c-acf2d6bcd8d3
        apiKey: 9e4a73b4-e404-48d2-8ad2-5c2ca42dcebd
        releaseName: ${{ steps.deploy-to-webapp.outputs.webapp-version }}
        message: 'experiment complete'
      
    - name: Start experiment
      uses: Azure/cli@v1
      with:
        inlineScript: az rest --method post --url https://management.azure.com/subscriptions/4668507d-0a5b-4ef7-9ca7-a10f2cc3103b/resourcegroups/deployApp/providers/microsoft.chaos/experiments/validateApp/start?api-version=2021-09-15-preview
    
    - name: Wait for experiment
      uses: jakejarvis/wait-action@v0.1.1
      with:
        time: 20m
      
    - name: App Insights experiment end
      uses: wictorwilen/application-insights-action@v1
      with:
        applicationId: 0e3aa4b6-48d3-4505-b65c-acf2d6bcd8d3
        apiKey: 9e4a73b4-e404-48d2-8ad2-5c2ca42dcebd
        releaseName: ${{ steps.deploy-to-webapp.outputs.webapp-version }}
        message: 'experiment complete'
